services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - make build-image
deploy:
  skip_cleanup: true
  provider: script
  script:
    - make push-image
  on:
    branch: master
