services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
deploy:
  skip_cleanup: true
  provider: script
  script:
    - bash ./deploy.sh
  on:
    branch: master
