services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
before_install:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
script:
  - docker build -t iamstefin/nginx-media -f ./nginx-media/Dockerfile ./nginx-media
  - docker build -t iamstefin/django-deployment -f ./myproject/Dockerfile ./myproject
deploy:
  skip_cleanup: true
  provider: script
  script:
    - bash ./deploy.sh
  on:
    branch: master
