apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ingress-service
  annotations:
    kubernetes.io/ingress.class: traefik

spec:
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          serviceName: django-deployment-cluster-ip-service
          servicePort: 8000
